### ISSUE TITLE
Setup Problem

### ISSUE THREAD

**Issue by avdohe** [bjoernalbers/MaScApp#1]
Hallo Björn,

suche schon seit langem eine Möglichkeit, Masc auf einem Mac in Verbindung mit Osirix zu nutzen.
Nun bin ich auf diese (scheinbar) einfache Lösung gestoßen.

Leider klappt es bei mir nicht so richtig. Bei der Installation der MASC APP im Befehl bin/setup bekomme ich den Fehler "bin/setup: line 5: bundle: command not found".

Ich meine eigentlich deiner Anleitung genau gefolgt zu sein. Muss allerdings gestehen, dass ich kein Consolenfreak bin.

Hast du einen Tip für mich?
System:
ElCapitan, XCode, Clone o.k., Entpacken der exe o.k., Installation der jar Datei o.k., Entpacken der App o.k., dann hängt es bei dem bin/setup. 

Danke,
Axel

**Comment by avdohe** [comment]
Hat sich schon erledigt. Nach ca. 2 Stunden "rumgefummel" in der Konsole mit ruby & Co ging es dann irgendwann. Habe jetzt das heiß ersehnte dmg.

Danke.

**Comment by bjoernalbers** [comment]
Hallo Axel,

danke für dein Feedback.
Dir fehlte vermutlich ein bestimmtes Rubygem namens *Bundler*.
Unter aktuellen Version von macOS lässt sich dieses mit folgendem Befehl installieren:

```
sudo gem install bundler --no-document -n /usr/local/bin
```

Gruß,
Björn

**Comment by bjoernalbers** [comment]
PS: Das setup-Skript enthält jetzt direkt o.g. Befehl: https://github.com/bjoernalbers/MaScApp/commit/8f13effde5767f3ad8df2230917df6c57ead5c10

**Comment by avdohe** [comment]
Ja das war’s (nach längerem suchen).

Wie wäre es mit einem kurzen Hinweis in der Doku?

Danke.

Axel

Von: Björn Albers [mailto:notifications@github.com]
Gesendet: Samstag, 21. Januar 2017 02:33
An: bjoernalbers/MaScApp <MaScApp@noreply.github.com>
Cc: von der Ohe, Axel <axel.vonderohe@jobjoy.de>; State change <state_change@noreply.github.com>
Betreff: Re: [bjoernalbers/MaScApp] Setup Problem (#1)


Hallo Axel,

danke für dein Feedback.
Dir fehlte vermutlich ein bestimmtes Rubygem namens Bundler.
Unter aktuellen Version von macOS lässt sich dieses mit folgendem Befehl installieren:

sudo gem install bundler --no-document -n /usr/local/bin

Gruß,
Björn

**Comment by bjoernalbers** [comment]
Ist schon durch das Setup-Skript erledigt (siehe oben)

**Comment by avdohe** [comment]
Hallo Björn,

darf ich dich noch einmal belästigen?
Ich habe inzwischen das von deinem Script bearbeitet Masc (von KV-Nordrhein) mit passender Anbindung bei einem Radiologen ausprobieren können.
Masc startet auch ohne Fehler, allerdings kann man sich nicht anmelden. Angeblich ist immer der User / Kennwort unbekannt.
Natürlich funktionieren die selben Anmeldedaten bei einer Windows-Arbeitsstation problemlos.
Könnten die Anmeldeprobleme an einer zu neuen Java Version liegen? Ich habe die neueste verfügbare genutzt.

Nach Aussage des Radiologen benötigt das Masc auch einen Netzwerklaufwerksbuchstaben V:, der hier auf einen VISUS PACS Router zeigt.
Der kann doch unter macOS / OSX nicht nachgebildet werden oder gibt es eine Möglichkeit, das irgendwie zu händeln?

Für ein paar Tips wäre ich dankbar.

Vielen Dank,
Axel



Von: Björn Albers [mailto:notifications@github.com]
Gesendet: Samstag, 21. Januar 2017 02:45
An: bjoernalbers/MaScApp <MaScApp@noreply.github.com>
Cc: von der Ohe, Axel <axel.vonderohe@jobjoy.de>; State change <state_change@noreply.github.com>
Betreff: Re: [bjoernalbers/MaScApp] Setup Problem (#1)


Ist schon durch das Setup-Skript erledigt (siehe oben)

**Comment by bjoernalbers** [comment]
Hi Axel,

ich war die letzte Tage AFK und versuche den Fehler später mal nachzustellen. Hang on...


Gruß,
Björn

**Comment by bjoernalbers** [comment]
Hi Axel,

ich habe nochmal eine Version gebaut.
Bitte mal hiermit testen und Rückmeldung geben: https://dl.dropboxusercontent.com/u/150292/masc_3.6.2.3.dmg

Zum Laufwerksproblem: Meines Wissens wird das Laufwerk global für die jeweilige Praxis konfiguriert.
Dadurch kann man leider keinen "Mischbetrieb" mit Windows & Mac fahren - Windows kann ja nichts mit `/Volumes/masc` anfangen, und der Mac nichts mit `V:\`.
Aus diesem Grund haben wir auch noch nicht umgestellt.
Am besten wäre es, wenn sich das Laufwerk einzeln je Arbeitsplatz überschreiben ließe.
D.h. es muss etwas in der MaSc geändert werden.

Gruß,
Björn
